apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hz4ttkwd3-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hz4ttkwd3-go 
  name: hz4ttkwd3-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hz4ttkwd3-go 
